name: forever_us_in_love
description: ForeverUsInLove - Dating & Marketplace Application Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Routing
  go_router: ^12.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Forms & Validation
  formz: ^0.6.1
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Camera & Image
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  
  # Location
  geolocator: ^10.1.0
  
  # Firebase (for notifications, auth, etc.)
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.3
  firebase_auth: ^4.14.0
  
  # Google Sign In
  google_sign_in: ^6.1.5
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.1
  
  # Animations
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.5
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
  
  # Fonts placeholders (to be added later)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
